name: Autopep8

on:
  push:
    branches: [Updated_2.0]
  pull_request:
    branches: [ Updated_2.0]

jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'

      - name: Install autopep8
        run: pip install autopep8

      - name: Run autopep8
        run: autopep8 --in-place --recursive .
