name: CI

on:
  push:
    branches:
      - Updated_2.0
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure your dependencies are listed here

    - name: Run tests with coverage
      run: |
        pip install pytest pytest-cov  # Ensure coverage tools are installed
        pytest --cov=your_module_name --cov-report=xml  # Adjust as necessary
