name: Style Check with Flake8

on:
  push:
    branches:
      - Updated_2.0
  pull_request:
    branches:
      - Updated_2.0

jobs:
  style_check:
    name: Style Check
    strategy:
      matrix:
        python-version:
          - 3.12.1

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Flake8
      run: pip install flake8

    - name: Run Flake8
      run: flake8 .  # Replace "." with the directory containing your Python files
